chore: test composite action take 7

diff --git a/.github/actions/create-pr/action.yml b/.github/actions/create-pr/action.yml
--- a/.github/actions/create-pr/action.yml
+++ b/.github/actions/create-pr/action.yml
@@ -26,22 +26,18 @@ runs:
     - id: adjust-path
       run: echo "${{ github.action_path }}" >> $GITHUB_PATH
       shell: bash
-    - id: test-input
-      run: echo "${FILES}"
-      env:
-        FILES: ${{ inputs.files }}
-      shell: bash
     - id: create-pr
       run: create_pr_for_staged_changes.sh "${FILES}"
       env:
         FILES: ${{ inputs.files }}
         TEMP_BRANCH_PREFIX: ${{ inputs.temp_branch_prefix }}
         GH_TOKEN: ${{ inputs.github_token }}
+        PR_TITLE: ${{ inputs.pull_request_title }}
       shell: bash
     - id: cleanup
       name: Cleanup orphaned branch
       if: failure()
-      run: git push origin --delete "${TEMP_BRANCH_PREFIX}-${GITHUB_RUN_ID}" || echo "Must have failed before creating temporary branch; no cleanup needed."
+      run: git push origin --delete "${TEMP_BRANCH_PREFIX}-${GITHUB_RUN_ID}" || echo "Must have failed before creating temporary branch; no cleanup needed." && exit 0
       env:
         TEMP_BRANCH_PREFIX: ${{ inputs.temp_branch_prefix }}
         GITHUB_RUN_ID: ${{ github.run_id }}
