chore: test composite action

diff --git a/.github/workflows/build_changelog.yml b/.github/workflows/build_changelog.yml
--- a/.github/workflows/build_changelog.yml
+++ b/.github/workflows/build_changelog.yml
@@ -34,17 +34,25 @@ jobs:
       - name: "Generate latest changelog"
         run: make changelog
       - name: Create PR
-        run: bash .github/scripts/create_pr_for_staged_changes.sh CHANGELOG.md
-        env:
-          PR_TITLE: "chore(ci): changelog rebuild"
-          TEMP_BRANCH_PREFIX: "ci-changelog"
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Cleanup orphaned branch
-        if: failure()
-        run: git push origin --delete "${TEMP_BRANCH_PREFIX}-${GITHUB_RUN_ID}" || echo "Must have failed before creating temporary branch; no cleanup needed."
-        env:
-          TEMP_BRANCH_PREFIX: "ci-changelog"
-          GITHUB_RUN_ID: ${{ github.run_id }}
+        uses: ./github/actions/create-pr
+        with:
+          files: CHANGELOG.md docs/index.md examples/
+          temp_branch_prefix: "ci-changelog"
+          pull_request_title: "chore(ci): changelog rebuild"
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Create PR
+      #   run: bash .github/scripts/create_pr_for_staged_changes.sh CHANGELOG.md
+      #   env:
+      #     PR_TITLE: "chore(ci): changelog rebuild"
+      #     TEMP_BRANCH_PREFIX: "ci-changelog"
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Cleanup orphaned branch
+      #   if: failure()
+      #   run: git push origin --delete "${TEMP_BRANCH_PREFIX}-${GITHUB_RUN_ID}" || echo "Must have failed before creating temporary branch; no cleanup needed."
+      #   env:
+      #     TEMP_BRANCH_PREFIX: "ci-changelog"
+      #     GITHUB_RUN_ID: ${{ github.run_id }}
 
   # changelog:
   #   uses: ./.github/workflows/reusable_publish_changelog.yml
