chore(ci): test cleanup update take 3

diff --git a/.github/workflows/build_changelog.yml b/.github/workflows/build_changelog.yml
--- a/.github/workflows/build_changelog.yml
+++ b/.github/workflows/build_changelog.yml
@@ -42,10 +42,10 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Cleanup orphaned branch
         if: failure()
-        run: git push origin --delete "${TEMP_BRANCH}" || echo "Must have failed before creating temporary branch; no cleanup needed."
+        run: git push origin --delete "${TEMP_BRANCH}-${GITHUB_RUN_ID}" || echo "Must have failed before creating temporary branch; no cleanup needed."
         env:
           TEMP_BRANCH_PREFIX: "ci-changelog"
-          TEMP_BRANCH: "${{ env.TEMP_BRANCH_PREFIX }}-${{ github.run_id }}"
+          GITHUB_RUN_ID: ${{ github.run_id }}
 
   # changelog:
   #   uses: ./.github/workflows/reusable_publish_changelog.yml
