chore: get a sample webhook payload for testing

diff --git a/.github/workflows/build_changelog.yml b/.github/workflows/build_changelog.yml
--- a/.github/workflows/build_changelog.yml
+++ b/.github/workflows/build_changelog.yml
@@ -42,9 +42,10 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           RUN_ID: ${{ github.run_id }}
+          GITHUB_EVENT: ${{ toJSON(github.event) }}
       - name: Cleanup orphaned branch
         if: failure()
-        run: git push origin --delete "${TEMP_BRANCH}"
+        run: git push origin --delete "${TEMP_BRANCH}" || echo "Must have failed before creating temporary branch; no cleanup needed."
         env:
           TEMP_BRANCH: "ci-changelog-${{ github.run_id}}"
 
